// this file is auto-generated. Run `make regenerate-types` to regenerate it.

import { CallbackReturn } from '../node/callback-return';
import { ExportsStyle } from '../node/exports-style';
import { FileExtensionInImport } from '../node/file-extension-in-import';
import { GlobalRequire } from '../node/global-require';
import { HandleCallbackErr } from '../node/handle-callback-err';
import { NoCallbackLiteral } from '../node/no-callback-literal';
import { NoDeprecatedApi } from '../node/no-deprecated-api';
import { NoExportsAssign } from '../node/no-exports-assign';
import { NoExtraneousImport } from '../node/no-extraneous-import';
import { NoExtraneousRequire } from '../node/no-extraneous-require';
import { NoMissingImport } from '../node/no-missing-import';
import { NoMissingRequire } from '../node/no-missing-require';
import { NoMixedRequires } from '../node/no-mixed-requires';
import { NoNewRequire } from '../node/no-new-require';
import { NoPathConcat } from '../node/no-path-concat';
import { NoProcessEnv } from '../node/no-process-env';
import { NoProcessExit } from '../node/no-process-exit';
import { NoRestrictedImport } from '../node/no-restricted-import';
import { NoRestrictedRequire } from '../node/no-restricted-require';
import { NoSync } from '../node/no-sync';
import { NoUnpublishedBin } from '../node/no-unpublished-bin';
import { NoUnpublishedImport } from '../node/no-unpublished-import';
import { NoUnpublishedRequire } from '../node/no-unpublished-require';
import { NoUnsupportedFeaturesEsBuiltins } from '../node/no-unsupported-features/es-builtins';
import { NoUnsupportedFeaturesEsSyntax } from '../node/no-unsupported-features/es-syntax';
import { NoUnsupportedFeaturesNodeBuiltins } from '../node/no-unsupported-features/node-builtins';
import { PreferGlobalBuffer } from '../node/prefer-global/buffer';
import { PreferGlobalConsole } from '../node/prefer-global/console';
import { PreferGlobalProcess } from '../node/prefer-global/process';
import { PreferGlobalTextDecoder } from '../node/prefer-global/text-decoder';
import { PreferGlobalTextEncoder } from '../node/prefer-global/text-encoder';
import { PreferGlobalUrlSearchParams } from '../node/prefer-global/url-search-params';
import { PreferGlobalUrl } from '../node/prefer-global/url';
import { PreferPromisesDns } from '../node/prefer-promises/dns';
import { PreferPromisesFs } from '../node/prefer-promises/fs';
import { ProcessExitAsThrow } from '../node/process-exit-as-throw';
import { Shebang } from '../node/shebang';

interface Node {
  'node/callback-return': CallbackReturn;
  'node/exports-style': ExportsStyle;
  'node/file-extension-in-import': FileExtensionInImport;
  'node/global-require': GlobalRequire;
  'node/handle-callback-err': HandleCallbackErr;
  'node/no-callback-literal': NoCallbackLiteral;
  'node/no-deprecated-api': NoDeprecatedApi;
  'node/no-exports-assign': NoExportsAssign;
  'node/no-extraneous-import': NoExtraneousImport;
  'node/no-extraneous-require': NoExtraneousRequire;
  'node/no-missing-import': NoMissingImport;
  'node/no-missing-require': NoMissingRequire;
  'node/no-mixed-requires': NoMixedRequires;
  'node/no-new-require': NoNewRequire;
  'node/no-path-concat': NoPathConcat;
  'node/no-process-env': NoProcessEnv;
  'node/no-process-exit': NoProcessExit;
  'node/no-restricted-import': NoRestrictedImport;
  'node/no-restricted-require': NoRestrictedRequire;
  'node/no-sync': NoSync;
  'node/no-unpublished-bin': NoUnpublishedBin;
  'node/no-unpublished-import': NoUnpublishedImport;
  'node/no-unpublished-require': NoUnpublishedRequire;
  'node/no-unsupported-features/es-builtins': NoUnsupportedFeaturesEsBuiltins;
  'node/no-unsupported-features/es-syntax': NoUnsupportedFeaturesEsSyntax;
  'node/no-unsupported-features/node-builtins': NoUnsupportedFeaturesNodeBuiltins;
  'node/prefer-global/buffer': PreferGlobalBuffer;
  'node/prefer-global/console': PreferGlobalConsole;
  'node/prefer-global/process': PreferGlobalProcess;
  'node/prefer-global/text-decoder': PreferGlobalTextDecoder;
  'node/prefer-global/text-encoder': PreferGlobalTextEncoder;
  'node/prefer-global/url-search-params': PreferGlobalUrlSearchParams;
  'node/prefer-global/url': PreferGlobalUrl;
  'node/prefer-promises/dns': PreferPromisesDns;
  'node/prefer-promises/fs': PreferPromisesFs;
  'node/process-exit-as-throw': ProcessExitAsThrow;
  'node/shebang': Shebang;
}

export { Node };
