// this file is auto-generated. Run `make regenerate-types` to regenerate it.

import { ConsistentTestIt } from '../jest/consistent-test-it';
import { ExpectExpect } from '../jest/expect-expect';
import { LowercaseName } from '../jest/lowercase-name';
import { NoAliasMethods } from '../jest/no-alias-methods';
import { NoCommentedOutTests } from '../jest/no-commented-out-tests';
import { NoDisabledTests } from '../jest/no-disabled-tests';
import { NoDuplicateHooks } from '../jest/no-duplicate-hooks';
import { NoExpectResolves } from '../jest/no-expect-resolves';
import { NoExport } from '../jest/no-export';
import { NoFocusedTests } from '../jest/no-focused-tests';
import { NoHooks } from '../jest/no-hooks';
import { NoIdenticalTitle } from '../jest/no-identical-title';
import { NoIf } from '../jest/no-if';
import { NoJasmineGlobals } from '../jest/no-jasmine-globals';
import { NoJestImport } from '../jest/no-jest-import';
import { NoLargeSnapshots } from '../jest/no-large-snapshots';
import { NoMocksImport } from '../jest/no-mocks-import';
import { NoStandaloneExpect } from '../jest/no-standalone-expect';
import { NoTestCallback } from '../jest/no-test-callback';
import { NoTestPrefixes } from '../jest/no-test-prefixes';
import { NoTestReturnStatement } from '../jest/no-test-return-statement';
import { NoTruthyFalsy } from '../jest/no-truthy-falsy';
import { NoTryExpect } from '../jest/no-try-expect';
import { PreferCalledWith } from '../jest/prefer-called-with';
import { PreferExpectAssertions } from '../jest/prefer-expect-assertions';
import { PreferHooksOnTop } from '../jest/prefer-hooks-on-top';
import { PreferInlineSnapshots } from '../jest/prefer-inline-snapshots';
import { PreferSpyOn } from '../jest/prefer-spy-on';
import { PreferStrictEqual } from '../jest/prefer-strict-equal';
import { PreferToBeNull } from '../jest/prefer-to-be-null';
import { PreferToBeUndefined } from '../jest/prefer-to-be-undefined';
import { PreferToContain } from '../jest/prefer-to-contain';
import { PreferToHaveLength } from '../jest/prefer-to-have-length';
import { PreferTodo } from '../jest/prefer-todo';
import { RequireToThrowMessage } from '../jest/require-to-throw-message';
import { RequireTopLevelDescribe } from '../jest/require-top-level-describe';
import { ValidDescribe } from '../jest/valid-describe';
import { ValidExpect } from '../jest/valid-expect';
import { ValidExpectInPromise } from '../jest/valid-expect-in-promise';
import { ValidTitle } from '../jest/valid-title';

interface Jest {
  'jest/consistent-test-it': ConsistentTestIt;
  'jest/expect-expect': ExpectExpect;
  'jest/lowercase-name': LowercaseName;
  'jest/no-alias-methods': NoAliasMethods;
  'jest/no-commented-out-tests': NoCommentedOutTests;
  'jest/no-disabled-tests': NoDisabledTests;
  'jest/no-duplicate-hooks': NoDuplicateHooks;
  'jest/no-expect-resolves': NoExpectResolves;
  'jest/no-export': NoExport;
  'jest/no-focused-tests': NoFocusedTests;
  'jest/no-hooks': NoHooks;
  'jest/no-identical-title': NoIdenticalTitle;
  'jest/no-if': NoIf;
  'jest/no-jasmine-globals': NoJasmineGlobals;
  'jest/no-jest-import': NoJestImport;
  'jest/no-large-snapshots': NoLargeSnapshots;
  'jest/no-mocks-import': NoMocksImport;
  'jest/no-standalone-expect': NoStandaloneExpect;
  'jest/no-test-callback': NoTestCallback;
  'jest/no-test-prefixes': NoTestPrefixes;
  'jest/no-test-return-statement': NoTestReturnStatement;
  'jest/no-truthy-falsy': NoTruthyFalsy;
  'jest/no-try-expect': NoTryExpect;
  'jest/prefer-called-with': PreferCalledWith;
  'jest/prefer-expect-assertions': PreferExpectAssertions;
  'jest/prefer-hooks-on-top': PreferHooksOnTop;
  'jest/prefer-inline-snapshots': PreferInlineSnapshots;
  'jest/prefer-spy-on': PreferSpyOn;
  'jest/prefer-strict-equal': PreferStrictEqual;
  'jest/prefer-to-be-null': PreferToBeNull;
  'jest/prefer-to-be-undefined': PreferToBeUndefined;
  'jest/prefer-to-contain': PreferToContain;
  'jest/prefer-to-have-length': PreferToHaveLength;
  'jest/prefer-todo': PreferTodo;
  'jest/require-to-throw-message': RequireToThrowMessage;
  'jest/require-top-level-describe': RequireTopLevelDescribe;
  'jest/valid-describe': ValidDescribe;
  'jest/valid-expect': ValidExpect;
  'jest/valid-expect-in-promise': ValidExpectInPromise;
  'jest/valid-title': ValidTitle;
}

export { Jest };
