// this file is auto-generated. Run `make regenerate-types` to regenerate it.

import { ConsistentTestIt } from '../jest/consistent-test-it';
import { ExpectExpect } from '../jest/expect-expect';
import { MaxExpects } from '../jest/max-expects';
import { MaxNestedDescribe } from '../jest/max-nested-describe';
import { NoAliasMethods } from '../jest/no-alias-methods';
import { NoCommentedOutTests } from '../jest/no-commented-out-tests';
import { NoConditionalExpect } from '../jest/no-conditional-expect';
import { NoConditionalInTest } from '../jest/no-conditional-in-test';
import { NoDeprecatedFunctions } from '../jest/no-deprecated-functions';
import { NoDisabledTests } from '../jest/no-disabled-tests';
import { NoDoneCallback } from '../jest/no-done-callback';
import { NoDuplicateHooks } from '../jest/no-duplicate-hooks';
import { NoExport } from '../jest/no-export';
import { NoFocusedTests } from '../jest/no-focused-tests';
import { NoHooks } from '../jest/no-hooks';
import { NoIdenticalTitle } from '../jest/no-identical-title';
import { NoInterpolationInSnapshots } from '../jest/no-interpolation-in-snapshots';
import { NoJasmineGlobals } from '../jest/no-jasmine-globals';
import { NoJestImport } from '../jest/no-jest-import';
import { NoLargeSnapshots } from '../jest/no-large-snapshots';
import { NoMocksImport } from '../jest/no-mocks-import';
import { NoRestrictedMatchers } from '../jest/no-restricted-matchers';
import { NoStandaloneExpect } from '../jest/no-standalone-expect';
import { NoTestPrefixes } from '../jest/no-test-prefixes';
import { NoTestReturnStatement } from '../jest/no-test-return-statement';
import { PreferCalledWith } from '../jest/prefer-called-with';
import { PreferComparisonMatcher } from '../jest/prefer-comparison-matcher';
import { PreferEqualityMatcher } from '../jest/prefer-equality-matcher';
import { PreferExpectAssertions } from '../jest/prefer-expect-assertions';
import { PreferExpectResolves } from '../jest/prefer-expect-resolves';
import { PreferHooksInOrder } from '../jest/prefer-hooks-in-order';
import { PreferHooksOnTop } from '../jest/prefer-hooks-on-top';
import { PreferLowercaseTitle } from '../jest/prefer-lowercase-title';
import { PreferMockPromiseShorthand } from '../jest/prefer-mock-promise-shorthand';
import { PreferSnapshotHint } from '../jest/prefer-snapshot-hint';
import { PreferSpyOn } from '../jest/prefer-spy-on';
import { PreferStrictEqual } from '../jest/prefer-strict-equal';
import { PreferToBe } from '../jest/prefer-to-be';
import { PreferToContain } from '../jest/prefer-to-contain';
import { PreferToHaveLength } from '../jest/prefer-to-have-length';
import { PreferTodo } from '../jest/prefer-todo';
import { RequireHook } from '../jest/require-hook';
import { RequireToThrowMessage } from '../jest/require-to-throw-message';
import { RequireTopLevelDescribe } from '../jest/require-top-level-describe';
import { UnboundMethod } from '../jest/unbound-method';
import { ValidDescribeCallback } from '../jest/valid-describe-callback';
import { ValidExpectInPromise } from '../jest/valid-expect-in-promise';
import { ValidExpect } from '../jest/valid-expect';
import { ValidTitle } from '../jest/valid-title';

interface Jest {
  'jest/consistent-test-it': ConsistentTestIt;
  'jest/expect-expect': ExpectExpect;
  'jest/max-expects': MaxExpects;
  'jest/max-nested-describe': MaxNestedDescribe;
  'jest/no-alias-methods': NoAliasMethods;
  'jest/no-commented-out-tests': NoCommentedOutTests;
  'jest/no-conditional-expect': NoConditionalExpect;
  'jest/no-conditional-in-test': NoConditionalInTest;
  'jest/no-deprecated-functions': NoDeprecatedFunctions;
  'jest/no-disabled-tests': NoDisabledTests;
  'jest/no-done-callback': NoDoneCallback;
  'jest/no-duplicate-hooks': NoDuplicateHooks;
  'jest/no-export': NoExport;
  'jest/no-focused-tests': NoFocusedTests;
  'jest/no-hooks': NoHooks;
  'jest/no-identical-title': NoIdenticalTitle;
  'jest/no-interpolation-in-snapshots': NoInterpolationInSnapshots;
  'jest/no-jasmine-globals': NoJasmineGlobals;
  'jest/no-jest-import': NoJestImport;
  'jest/no-large-snapshots': NoLargeSnapshots;
  'jest/no-mocks-import': NoMocksImport;
  'jest/no-restricted-matchers': NoRestrictedMatchers;
  'jest/no-standalone-expect': NoStandaloneExpect;
  'jest/no-test-prefixes': NoTestPrefixes;
  'jest/no-test-return-statement': NoTestReturnStatement;
  'jest/prefer-called-with': PreferCalledWith;
  'jest/prefer-comparison-matcher': PreferComparisonMatcher;
  'jest/prefer-equality-matcher': PreferEqualityMatcher;
  'jest/prefer-expect-assertions': PreferExpectAssertions;
  'jest/prefer-expect-resolves': PreferExpectResolves;
  'jest/prefer-hooks-in-order': PreferHooksInOrder;
  'jest/prefer-hooks-on-top': PreferHooksOnTop;
  'jest/prefer-lowercase-title': PreferLowercaseTitle;
  'jest/prefer-mock-promise-shorthand': PreferMockPromiseShorthand;
  'jest/prefer-snapshot-hint': PreferSnapshotHint;
  'jest/prefer-spy-on': PreferSpyOn;
  'jest/prefer-strict-equal': PreferStrictEqual;
  'jest/prefer-to-be': PreferToBe;
  'jest/prefer-to-contain': PreferToContain;
  'jest/prefer-to-have-length': PreferToHaveLength;
  'jest/prefer-todo': PreferTodo;
  'jest/require-hook': RequireHook;
  'jest/require-to-throw-message': RequireToThrowMessage;
  'jest/require-top-level-describe': RequireTopLevelDescribe;
  'jest/unbound-method': UnboundMethod;
  'jest/valid-describe-callback': ValidDescribeCallback;
  'jest/valid-expect-in-promise': ValidExpectInPromise;
  'jest/valid-expect': ValidExpect;
  'jest/valid-title': ValidTitle;
}

export { Jest };
