// this file is auto-generated. Run `make regenerate-types` to regenerate it.

import { NoUnresolved } from '../import/no-unresolved';
import { Named } from '../import/named';
import { Default } from '../import/default';
import { Namespace } from '../import/namespace';
import { NoNamespace } from '../import/no-namespace';
import { Export } from '../import/export';
import { NoMutableExports } from '../import/no-mutable-exports';
import { Extensions } from '../import/extensions';
import { NoRestrictedPaths } from '../import/no-restricted-paths';
import { NoInternalModules } from '../import/no-internal-modules';
import { GroupExports } from '../import/group-exports';
import { NoRelativePackages } from '../import/no-relative-packages';
import { NoRelativeParentImports } from '../import/no-relative-parent-imports';
import { NoSelfImport } from '../import/no-self-import';
import { NoCycle } from '../import/no-cycle';
import { NoNamedDefault } from '../import/no-named-default';
import { NoNamedAsDefault } from '../import/no-named-as-default';
import { NoNamedAsDefaultMember } from '../import/no-named-as-default-member';
import { NoAnonymousDefaultExport } from '../import/no-anonymous-default-export';
import { NoUnusedModules } from '../import/no-unused-modules';
import { NoCommonjs } from '../import/no-commonjs';
import { NoAmd } from '../import/no-amd';
import { NoDuplicates } from '../import/no-duplicates';
import { First } from '../import/first';
import { MaxDependencies } from '../import/max-dependencies';
import { NoExtraneousDependencies } from '../import/no-extraneous-dependencies';
import { NoAbsolutePath } from '../import/no-absolute-path';
import { NoNodejsModules } from '../import/no-nodejs-modules';
import { NoWebpackLoaderSyntax } from '../import/no-webpack-loader-syntax';
import { Order } from '../import/order';
import { NewlineAfterImport } from '../import/newline-after-import';
import { PreferDefaultExport } from '../import/prefer-default-export';
import { NoDefaultExport } from '../import/no-default-export';
import { NoNamedExport } from '../import/no-named-export';
import { NoDynamicRequire } from '../import/no-dynamic-require';
import { Unambiguous } from '../import/unambiguous';
import { NoUnassignedImport } from '../import/no-unassigned-import';
import { NoUselessPathSegments } from '../import/no-useless-path-segments';
import { DynamicImportChunkname } from '../import/dynamic-import-chunkname';
import { NoImportModuleExports } from '../import/no-import-module-exports';
import { ExportsLast } from '../import/exports-last';
import { NoDeprecated } from '../import/no-deprecated';

interface Import {
  'import/no-unresolved': NoUnresolved;
  'import/named': Named;
  'import/default': Default;
  'import/namespace': Namespace;
  'import/no-namespace': NoNamespace;
  'import/export': Export;
  'import/no-mutable-exports': NoMutableExports;
  'import/extensions': Extensions;
  'import/no-restricted-paths': NoRestrictedPaths;
  'import/no-internal-modules': NoInternalModules;
  'import/group-exports': GroupExports;
  'import/no-relative-packages': NoRelativePackages;
  'import/no-relative-parent-imports': NoRelativeParentImports;
  'import/no-self-import': NoSelfImport;
  'import/no-cycle': NoCycle;
  'import/no-named-default': NoNamedDefault;
  'import/no-named-as-default': NoNamedAsDefault;
  'import/no-named-as-default-member': NoNamedAsDefaultMember;
  'import/no-anonymous-default-export': NoAnonymousDefaultExport;
  'import/no-unused-modules': NoUnusedModules;
  'import/no-commonjs': NoCommonjs;
  'import/no-amd': NoAmd;
  'import/no-duplicates': NoDuplicates;
  'import/first': First;
  'import/max-dependencies': MaxDependencies;
  'import/no-extraneous-dependencies': NoExtraneousDependencies;
  'import/no-absolute-path': NoAbsolutePath;
  'import/no-nodejs-modules': NoNodejsModules;
  'import/no-webpack-loader-syntax': NoWebpackLoaderSyntax;
  'import/order': Order;
  'import/newline-after-import': NewlineAfterImport;
  'import/prefer-default-export': PreferDefaultExport;
  'import/no-default-export': NoDefaultExport;
  'import/no-named-export': NoNamedExport;
  'import/no-dynamic-require': NoDynamicRequire;
  'import/unambiguous': Unambiguous;
  'import/no-unassigned-import': NoUnassignedImport;
  'import/no-useless-path-segments': NoUselessPathSegments;
  'import/dynamic-import-chunkname': DynamicImportChunkname;
  'import/no-import-module-exports': NoImportModuleExports;
  'import/exports-last': ExportsLast;
  'import/no-deprecated': NoDeprecated;
}

export { Import };
