// this file is auto-generated. Run `make regenerate-types` to regenerate it.

import { AccessorPairs } from '../eslint/accessor-pairs';
import { ArrayBracketNewline } from '../eslint/array-bracket-newline';
import { ArrayBracketSpacing } from '../eslint/array-bracket-spacing';
import { ArrayCallbackReturn } from '../eslint/array-callback-return';
import { ArrayElementNewline } from '../eslint/array-element-newline';
import { ArrowBodyStyle } from '../eslint/arrow-body-style';
import { ArrowParens } from '../eslint/arrow-parens';
import { ArrowSpacing } from '../eslint/arrow-spacing';
import { BlockScopedVar } from '../eslint/block-scoped-var';
import { BlockSpacing } from '../eslint/block-spacing';
import { BraceStyle } from '../eslint/brace-style';
import { CallbackReturn } from '../eslint/callback-return';
import { Camelcase } from '../eslint/camelcase';
import { CapitalizedComments } from '../eslint/capitalized-comments';
import { ClassMethodsUseThis } from '../eslint/class-methods-use-this';
import { CommaDangle } from '../eslint/comma-dangle';
import { CommaSpacing } from '../eslint/comma-spacing';
import { CommaStyle } from '../eslint/comma-style';
import { Complexity } from '../eslint/complexity';
import { ComputedPropertySpacing } from '../eslint/computed-property-spacing';
import { ConsistentReturn } from '../eslint/consistent-return';
import { ConsistentThis } from '../eslint/consistent-this';
import { ConstructorSuper } from '../eslint/constructor-super';
import { Curly } from '../eslint/curly';
import { DefaultCase } from '../eslint/default-case';
import { DefaultParamLast } from '../eslint/default-param-last';
import { DotLocation } from '../eslint/dot-location';
import { DotNotation } from '../eslint/dot-notation';
import { EolLast } from '../eslint/eol-last';
import { Eqeqeq } from '../eslint/eqeqeq';
import { ForDirection } from '../eslint/for-direction';
import { FuncCallSpacing } from '../eslint/func-call-spacing';
import { FuncNameMatching } from '../eslint/func-name-matching';
import { FuncNames } from '../eslint/func-names';
import { FuncStyle } from '../eslint/func-style';
import { FunctionCallArgumentNewline } from '../eslint/function-call-argument-newline';
import { FunctionParenNewline } from '../eslint/function-paren-newline';
import { GeneratorStarSpacing } from '../eslint/generator-star-spacing';
import { GetterReturn } from '../eslint/getter-return';
import { GlobalRequire } from '../eslint/global-require';
import { GroupedAccessorPairs } from '../eslint/grouped-accessor-pairs';
import { GuardForIn } from '../eslint/guard-for-in';
import { HandleCallbackErr } from '../eslint/handle-callback-err';
import { IdBlacklist } from '../eslint/id-blacklist';
import { IdLength } from '../eslint/id-length';
import { IdMatch } from '../eslint/id-match';
import { ImplicitArrowLinebreak } from '../eslint/implicit-arrow-linebreak';
import { Indent } from '../eslint/indent';
import { InitDeclarations } from '../eslint/init-declarations';
import { JsxQuotes } from '../eslint/jsx-quotes';
import { KeySpacing } from '../eslint/key-spacing';
import { KeywordSpacing } from '../eslint/keyword-spacing';
import { LineCommentPosition } from '../eslint/line-comment-position';
import { LinebreakStyle } from '../eslint/linebreak-style';
import { LinesAroundComment } from '../eslint/lines-around-comment';
import { LinesBetweenClassMembers } from '../eslint/lines-between-class-members';
import { MaxClassesPerFile } from '../eslint/max-classes-per-file';
import { MaxDepth } from '../eslint/max-depth';
import { MaxLen } from '../eslint/max-len';
import { MaxLines } from '../eslint/max-lines';
import { MaxLinesPerFunction } from '../eslint/max-lines-per-function';
import { MaxNestedCallbacks } from '../eslint/max-nested-callbacks';
import { MaxParams } from '../eslint/max-params';
import { MaxStatements } from '../eslint/max-statements';
import { MaxStatementsPerLine } from '../eslint/max-statements-per-line';
import { MultilineCommentStyle } from '../eslint/multiline-comment-style';
import { MultilineTernary } from '../eslint/multiline-ternary';
import { NewCap } from '../eslint/new-cap';
import { NewParens } from '../eslint/new-parens';
import { NewlinePerChainedCall } from '../eslint/newline-per-chained-call';
import { NoAlert } from '../eslint/no-alert';
import { NoArrayConstructor } from '../eslint/no-array-constructor';
import { NoAsyncPromiseExecutor } from '../eslint/no-async-promise-executor';
import { NoAwaitInLoop } from '../eslint/no-await-in-loop';
import { NoBitwise } from '../eslint/no-bitwise';
import { NoBufferConstructor } from '../eslint/no-buffer-constructor';
import { NoCaller } from '../eslint/no-caller';
import { NoCaseDeclarations } from '../eslint/no-case-declarations';
import { NoClassAssign } from '../eslint/no-class-assign';
import { NoCompareNegZero } from '../eslint/no-compare-neg-zero';
import { NoCondAssign } from '../eslint/no-cond-assign';
import { NoConfusingArrow } from '../eslint/no-confusing-arrow';
import { NoConsole } from '../eslint/no-console';
import { NoConstAssign } from '../eslint/no-const-assign';
import { NoConstantCondition } from '../eslint/no-constant-condition';
import { NoConstructorReturn } from '../eslint/no-constructor-return';
import { NoContinue } from '../eslint/no-continue';
import { NoControlRegex } from '../eslint/no-control-regex';
import { NoDebugger } from '../eslint/no-debugger';
import { NoDeleteVar } from '../eslint/no-delete-var';
import { NoDivRegex } from '../eslint/no-div-regex';
import { NoDupeArgs } from '../eslint/no-dupe-args';
import { NoDupeClassMembers } from '../eslint/no-dupe-class-members';
import { NoDupeElseIf } from '../eslint/no-dupe-else-if';
import { NoDupeKeys } from '../eslint/no-dupe-keys';
import { NoDuplicateCase } from '../eslint/no-duplicate-case';
import { NoDuplicateImports } from '../eslint/no-duplicate-imports';
import { NoElseReturn } from '../eslint/no-else-return';
import { NoEmpty } from '../eslint/no-empty';
import { NoEmptyCharacterClass } from '../eslint/no-empty-character-class';
import { NoEmptyFunction } from '../eslint/no-empty-function';
import { NoEmptyPattern } from '../eslint/no-empty-pattern';
import { NoEqNull } from '../eslint/no-eq-null';
import { NoEval } from '../eslint/no-eval';
import { NoExAssign } from '../eslint/no-ex-assign';
import { NoExtendNative } from '../eslint/no-extend-native';
import { NoExtraBind } from '../eslint/no-extra-bind';
import { NoExtraBooleanCast } from '../eslint/no-extra-boolean-cast';
import { NoExtraLabel } from '../eslint/no-extra-label';
import { NoExtraParens } from '../eslint/no-extra-parens';
import { NoExtraSemi } from '../eslint/no-extra-semi';
import { NoFallthrough } from '../eslint/no-fallthrough';
import { NoFloatingDecimal } from '../eslint/no-floating-decimal';
import { NoFuncAssign } from '../eslint/no-func-assign';
import { NoGlobalAssign } from '../eslint/no-global-assign';
import { NoImplicitCoercion } from '../eslint/no-implicit-coercion';
import { NoImplicitGlobals } from '../eslint/no-implicit-globals';
import { NoImpliedEval } from '../eslint/no-implied-eval';
import { NoImportAssign } from '../eslint/no-import-assign';
import { NoInlineComments } from '../eslint/no-inline-comments';
import { NoInnerDeclarations } from '../eslint/no-inner-declarations';
import { NoInvalidRegexp } from '../eslint/no-invalid-regexp';
import { NoInvalidThis } from '../eslint/no-invalid-this';
import { NoIrregularWhitespace } from '../eslint/no-irregular-whitespace';
import { NoIterator } from '../eslint/no-iterator';
import { NoLabelVar } from '../eslint/no-label-var';
import { NoLabels } from '../eslint/no-labels';
import { NoLoneBlocks } from '../eslint/no-lone-blocks';
import { NoLonelyIf } from '../eslint/no-lonely-if';
import { NoLoopFunc } from '../eslint/no-loop-func';
import { NoMagicNumbers } from '../eslint/no-magic-numbers';
import { NoMisleadingCharacterClass } from '../eslint/no-misleading-character-class';
import { NoMixedOperators } from '../eslint/no-mixed-operators';
import { NoMixedRequires } from '../eslint/no-mixed-requires';
import { NoMixedSpacesAndTabs } from '../eslint/no-mixed-spaces-and-tabs';
import { NoMultiAssign } from '../eslint/no-multi-assign';
import { NoMultiSpaces } from '../eslint/no-multi-spaces';
import { NoMultiStr } from '../eslint/no-multi-str';
import { NoMultipleEmptyLines } from '../eslint/no-multiple-empty-lines';
import { NoNegatedCondition } from '../eslint/no-negated-condition';
import { NoNestedTernary } from '../eslint/no-nested-ternary';
import { NoNew } from '../eslint/no-new';
import { NoNewFunc } from '../eslint/no-new-func';
import { NoNewObject } from '../eslint/no-new-object';
import { NoNewRequire } from '../eslint/no-new-require';
import { NoNewSymbol } from '../eslint/no-new-symbol';
import { NoNewWrappers } from '../eslint/no-new-wrappers';
import { NoObjCalls } from '../eslint/no-obj-calls';
import { NoOctal } from '../eslint/no-octal';
import { NoOctalEscape } from '../eslint/no-octal-escape';
import { NoParamReassign } from '../eslint/no-param-reassign';
import { NoPathConcat } from '../eslint/no-path-concat';
import { NoPlusplus } from '../eslint/no-plusplus';
import { NoProcessEnv } from '../eslint/no-process-env';
import { NoProcessExit } from '../eslint/no-process-exit';
import { NoProto } from '../eslint/no-proto';
import { NoPrototypeBuiltins } from '../eslint/no-prototype-builtins';
import { NoRedeclare } from '../eslint/no-redeclare';
import { NoRegexSpaces } from '../eslint/no-regex-spaces';
import { NoRestrictedGlobals } from '../eslint/no-restricted-globals';
import { NoRestrictedImports } from '../eslint/no-restricted-imports';
import { NoRestrictedModules } from '../eslint/no-restricted-modules';
import { NoRestrictedProperties } from '../eslint/no-restricted-properties';
import { NoRestrictedSyntax } from '../eslint/no-restricted-syntax';
import { NoReturnAssign } from '../eslint/no-return-assign';
import { NoReturnAwait } from '../eslint/no-return-await';
import { NoScriptUrl } from '../eslint/no-script-url';
import { NoSelfAssign } from '../eslint/no-self-assign';
import { NoSelfCompare } from '../eslint/no-self-compare';
import { NoSequences } from '../eslint/no-sequences';
import { NoSetterReturn } from '../eslint/no-setter-return';
import { NoShadow } from '../eslint/no-shadow';
import { NoShadowRestrictedNames } from '../eslint/no-shadow-restricted-names';
import { NoSparseArrays } from '../eslint/no-sparse-arrays';
import { NoSync } from '../eslint/no-sync';
import { NoTabs } from '../eslint/no-tabs';
import { NoTemplateCurlyInString } from '../eslint/no-template-curly-in-string';
import { NoTernary } from '../eslint/no-ternary';
import { NoThisBeforeSuper } from '../eslint/no-this-before-super';
import { NoThrowLiteral } from '../eslint/no-throw-literal';
import { NoTrailingSpaces } from '../eslint/no-trailing-spaces';
import { NoUndef } from '../eslint/no-undef';
import { NoUndefInit } from '../eslint/no-undef-init';
import { NoUndefined } from '../eslint/no-undefined';
import { NoUnderscoreDangle } from '../eslint/no-underscore-dangle';
import { NoUnexpectedMultiline } from '../eslint/no-unexpected-multiline';
import { NoUnmodifiedLoopCondition } from '../eslint/no-unmodified-loop-condition';
import { NoUnneededTernary } from '../eslint/no-unneeded-ternary';
import { NoUnreachable } from '../eslint/no-unreachable';
import { NoUnsafeFinally } from '../eslint/no-unsafe-finally';
import { NoUnsafeNegation } from '../eslint/no-unsafe-negation';
import { NoUnusedExpressions } from '../eslint/no-unused-expressions';
import { NoUnusedLabels } from '../eslint/no-unused-labels';
import { NoUnusedVars } from '../eslint/no-unused-vars';
import { NoUseBeforeDefine } from '../eslint/no-use-before-define';
import { NoUselessCall } from '../eslint/no-useless-call';
import { NoUselessCatch } from '../eslint/no-useless-catch';
import { NoUselessComputedKey } from '../eslint/no-useless-computed-key';
import { NoUselessConcat } from '../eslint/no-useless-concat';
import { NoUselessConstructor } from '../eslint/no-useless-constructor';
import { NoUselessEscape } from '../eslint/no-useless-escape';
import { NoUselessRename } from '../eslint/no-useless-rename';
import { NoUselessReturn } from '../eslint/no-useless-return';
import { NoVar } from '../eslint/no-var';
import { NoVoid } from '../eslint/no-void';
import { NoWarningComments } from '../eslint/no-warning-comments';
import { NoWhitespaceBeforeProperty } from '../eslint/no-whitespace-before-property';
import { NoWith } from '../eslint/no-with';
import { NonblockStatementBodyPosition } from '../eslint/nonblock-statement-body-position';
import { ObjectCurlyNewline } from '../eslint/object-curly-newline';
import { ObjectCurlySpacing } from '../eslint/object-curly-spacing';
import { ObjectPropertyNewline } from '../eslint/object-property-newline';
import { ObjectShorthand } from '../eslint/object-shorthand';
import { OneVar } from '../eslint/one-var';
import { OneVarDeclarationPerLine } from '../eslint/one-var-declaration-per-line';
import { OperatorAssignment } from '../eslint/operator-assignment';
import { OperatorLinebreak } from '../eslint/operator-linebreak';
import { PaddedBlocks } from '../eslint/padded-blocks';
import { PaddingLineBetweenStatements } from '../eslint/padding-line-between-statements';
import { PreferArrowCallback } from '../eslint/prefer-arrow-callback';
import { PreferConst } from '../eslint/prefer-const';
import { PreferDestructuring } from '../eslint/prefer-destructuring';
import { PreferExponentiationOperator } from '../eslint/prefer-exponentiation-operator';
import { PreferNamedCaptureGroup } from '../eslint/prefer-named-capture-group';
import { PreferNumericLiterals } from '../eslint/prefer-numeric-literals';
import { PreferObjectSpread } from '../eslint/prefer-object-spread';
import { PreferPromiseRejectErrors } from '../eslint/prefer-promise-reject-errors';
import { PreferRegexLiterals } from '../eslint/prefer-regex-literals';
import { PreferRestParams } from '../eslint/prefer-rest-params';
import { PreferSpread } from '../eslint/prefer-spread';
import { PreferTemplate } from '../eslint/prefer-template';
import { QuoteProps } from '../eslint/quote-props';
import { Quotes } from '../eslint/quotes';
import { Radix } from '../eslint/radix';
import { RequireAtomicUpdates } from '../eslint/require-atomic-updates';
import { RequireAwait } from '../eslint/require-await';
import { RequireUnicodeRegexp } from '../eslint/require-unicode-regexp';
import { RequireYield } from '../eslint/require-yield';
import { RestSpreadSpacing } from '../eslint/rest-spread-spacing';
import { Semi } from '../eslint/semi';
import { SemiSpacing } from '../eslint/semi-spacing';
import { SemiStyle } from '../eslint/semi-style';
import { SortImports } from '../eslint/sort-imports';
import { SortKeys } from '../eslint/sort-keys';
import { SortVars } from '../eslint/sort-vars';
import { SpaceBeforeBlocks } from '../eslint/space-before-blocks';
import { SpaceBeforeFunctionParen } from '../eslint/space-before-function-paren';
import { SpaceInParens } from '../eslint/space-in-parens';
import { SpaceInfixOps } from '../eslint/space-infix-ops';
import { SpaceUnaryOps } from '../eslint/space-unary-ops';
import { SpacedComment } from '../eslint/spaced-comment';
import { Strict } from '../eslint/strict';
import { SwitchColonSpacing } from '../eslint/switch-colon-spacing';
import { SymbolDescription } from '../eslint/symbol-description';
import { TemplateCurlySpacing } from '../eslint/template-curly-spacing';
import { TemplateTagSpacing } from '../eslint/template-tag-spacing';
import { UnicodeBom } from '../eslint/unicode-bom';
import { UseIsnan } from '../eslint/use-isnan';
import { ValidTypeof } from '../eslint/valid-typeof';
import { VarsOnTop } from '../eslint/vars-on-top';
import { WrapIife } from '../eslint/wrap-iife';
import { WrapRegex } from '../eslint/wrap-regex';
import { YieldStarSpacing } from '../eslint/yield-star-spacing';
import { Yoda } from '../eslint/yoda';

interface Eslint {
  'accessor-pairs': AccessorPairs;
  'array-bracket-newline': ArrayBracketNewline;
  'array-bracket-spacing': ArrayBracketSpacing;
  'array-callback-return': ArrayCallbackReturn;
  'array-element-newline': ArrayElementNewline;
  'arrow-body-style': ArrowBodyStyle;
  'arrow-parens': ArrowParens;
  'arrow-spacing': ArrowSpacing;
  'block-scoped-var': BlockScopedVar;
  'block-spacing': BlockSpacing;
  'brace-style': BraceStyle;
  'callback-return': CallbackReturn;
  camelcase: Camelcase;
  'capitalized-comments': CapitalizedComments;
  'class-methods-use-this': ClassMethodsUseThis;
  'comma-dangle': CommaDangle;
  'comma-spacing': CommaSpacing;
  'comma-style': CommaStyle;
  complexity: Complexity;
  'computed-property-spacing': ComputedPropertySpacing;
  'consistent-return': ConsistentReturn;
  'consistent-this': ConsistentThis;
  'constructor-super': ConstructorSuper;
  curly: Curly;
  'default-case': DefaultCase;
  'default-param-last': DefaultParamLast;
  'dot-location': DotLocation;
  'dot-notation': DotNotation;
  'eol-last': EolLast;
  eqeqeq: Eqeqeq;
  'for-direction': ForDirection;
  'func-call-spacing': FuncCallSpacing;
  'func-name-matching': FuncNameMatching;
  'func-names': FuncNames;
  'func-style': FuncStyle;
  'function-call-argument-newline': FunctionCallArgumentNewline;
  'function-paren-newline': FunctionParenNewline;
  'generator-star-spacing': GeneratorStarSpacing;
  'getter-return': GetterReturn;
  'global-require': GlobalRequire;
  'grouped-accessor-pairs': GroupedAccessorPairs;
  'guard-for-in': GuardForIn;
  'handle-callback-err': HandleCallbackErr;
  'id-blacklist': IdBlacklist;
  'id-length': IdLength;
  'id-match': IdMatch;
  'implicit-arrow-linebreak': ImplicitArrowLinebreak;
  indent: Indent;
  'init-declarations': InitDeclarations;
  'jsx-quotes': JsxQuotes;
  'key-spacing': KeySpacing;
  'keyword-spacing': KeywordSpacing;
  'line-comment-position': LineCommentPosition;
  'linebreak-style': LinebreakStyle;
  'lines-around-comment': LinesAroundComment;
  'lines-between-class-members': LinesBetweenClassMembers;
  'max-classes-per-file': MaxClassesPerFile;
  'max-depth': MaxDepth;
  'max-len': MaxLen;
  'max-lines': MaxLines;
  'max-lines-per-function': MaxLinesPerFunction;
  'max-nested-callbacks': MaxNestedCallbacks;
  'max-params': MaxParams;
  'max-statements': MaxStatements;
  'max-statements-per-line': MaxStatementsPerLine;
  'multiline-comment-style': MultilineCommentStyle;
  'multiline-ternary': MultilineTernary;
  'new-cap': NewCap;
  'new-parens': NewParens;
  'newline-per-chained-call': NewlinePerChainedCall;
  'no-alert': NoAlert;
  'no-array-constructor': NoArrayConstructor;
  'no-async-promise-executor': NoAsyncPromiseExecutor;
  'no-await-in-loop': NoAwaitInLoop;
  'no-bitwise': NoBitwise;
  'no-buffer-constructor': NoBufferConstructor;
  'no-caller': NoCaller;
  'no-case-declarations': NoCaseDeclarations;
  'no-class-assign': NoClassAssign;
  'no-compare-neg-zero': NoCompareNegZero;
  'no-cond-assign': NoCondAssign;
  'no-confusing-arrow': NoConfusingArrow;
  'no-console': NoConsole;
  'no-const-assign': NoConstAssign;
  'no-constant-condition': NoConstantCondition;
  'no-constructor-return': NoConstructorReturn;
  'no-continue': NoContinue;
  'no-control-regex': NoControlRegex;
  'no-debugger': NoDebugger;
  'no-delete-var': NoDeleteVar;
  'no-div-regex': NoDivRegex;
  'no-dupe-args': NoDupeArgs;
  'no-dupe-class-members': NoDupeClassMembers;
  'no-dupe-else-if': NoDupeElseIf;
  'no-dupe-keys': NoDupeKeys;
  'no-duplicate-case': NoDuplicateCase;
  'no-duplicate-imports': NoDuplicateImports;
  'no-else-return': NoElseReturn;
  'no-empty': NoEmpty;
  'no-empty-character-class': NoEmptyCharacterClass;
  'no-empty-function': NoEmptyFunction;
  'no-empty-pattern': NoEmptyPattern;
  'no-eq-null': NoEqNull;
  'no-eval': NoEval;
  'no-ex-assign': NoExAssign;
  'no-extend-native': NoExtendNative;
  'no-extra-bind': NoExtraBind;
  'no-extra-boolean-cast': NoExtraBooleanCast;
  'no-extra-label': NoExtraLabel;
  'no-extra-parens': NoExtraParens;
  'no-extra-semi': NoExtraSemi;
  'no-fallthrough': NoFallthrough;
  'no-floating-decimal': NoFloatingDecimal;
  'no-func-assign': NoFuncAssign;
  'no-global-assign': NoGlobalAssign;
  'no-implicit-coercion': NoImplicitCoercion;
  'no-implicit-globals': NoImplicitGlobals;
  'no-implied-eval': NoImpliedEval;
  'no-import-assign': NoImportAssign;
  'no-inline-comments': NoInlineComments;
  'no-inner-declarations': NoInnerDeclarations;
  'no-invalid-regexp': NoInvalidRegexp;
  'no-invalid-this': NoInvalidThis;
  'no-irregular-whitespace': NoIrregularWhitespace;
  'no-iterator': NoIterator;
  'no-label-var': NoLabelVar;
  'no-labels': NoLabels;
  'no-lone-blocks': NoLoneBlocks;
  'no-lonely-if': NoLonelyIf;
  'no-loop-func': NoLoopFunc;
  'no-magic-numbers': NoMagicNumbers;
  'no-misleading-character-class': NoMisleadingCharacterClass;
  'no-mixed-operators': NoMixedOperators;
  'no-mixed-requires': NoMixedRequires;
  'no-mixed-spaces-and-tabs': NoMixedSpacesAndTabs;
  'no-multi-assign': NoMultiAssign;
  'no-multi-spaces': NoMultiSpaces;
  'no-multi-str': NoMultiStr;
  'no-multiple-empty-lines': NoMultipleEmptyLines;
  'no-negated-condition': NoNegatedCondition;
  'no-nested-ternary': NoNestedTernary;
  'no-new': NoNew;
  'no-new-func': NoNewFunc;
  'no-new-object': NoNewObject;
  'no-new-require': NoNewRequire;
  'no-new-symbol': NoNewSymbol;
  'no-new-wrappers': NoNewWrappers;
  'no-obj-calls': NoObjCalls;
  'no-octal': NoOctal;
  'no-octal-escape': NoOctalEscape;
  'no-param-reassign': NoParamReassign;
  'no-path-concat': NoPathConcat;
  'no-plusplus': NoPlusplus;
  'no-process-env': NoProcessEnv;
  'no-process-exit': NoProcessExit;
  'no-proto': NoProto;
  'no-prototype-builtins': NoPrototypeBuiltins;
  'no-redeclare': NoRedeclare;
  'no-regex-spaces': NoRegexSpaces;
  'no-restricted-globals': NoRestrictedGlobals;
  'no-restricted-imports': NoRestrictedImports;
  'no-restricted-modules': NoRestrictedModules;
  'no-restricted-properties': NoRestrictedProperties;
  'no-restricted-syntax': NoRestrictedSyntax;
  'no-return-assign': NoReturnAssign;
  'no-return-await': NoReturnAwait;
  'no-script-url': NoScriptUrl;
  'no-self-assign': NoSelfAssign;
  'no-self-compare': NoSelfCompare;
  'no-sequences': NoSequences;
  'no-setter-return': NoSetterReturn;
  'no-shadow': NoShadow;
  'no-shadow-restricted-names': NoShadowRestrictedNames;
  'no-sparse-arrays': NoSparseArrays;
  'no-sync': NoSync;
  'no-tabs': NoTabs;
  'no-template-curly-in-string': NoTemplateCurlyInString;
  'no-ternary': NoTernary;
  'no-this-before-super': NoThisBeforeSuper;
  'no-throw-literal': NoThrowLiteral;
  'no-trailing-spaces': NoTrailingSpaces;
  'no-undef': NoUndef;
  'no-undef-init': NoUndefInit;
  'no-undefined': NoUndefined;
  'no-underscore-dangle': NoUnderscoreDangle;
  'no-unexpected-multiline': NoUnexpectedMultiline;
  'no-unmodified-loop-condition': NoUnmodifiedLoopCondition;
  'no-unneeded-ternary': NoUnneededTernary;
  'no-unreachable': NoUnreachable;
  'no-unsafe-finally': NoUnsafeFinally;
  'no-unsafe-negation': NoUnsafeNegation;
  'no-unused-expressions': NoUnusedExpressions;
  'no-unused-labels': NoUnusedLabels;
  'no-unused-vars': NoUnusedVars;
  'no-use-before-define': NoUseBeforeDefine;
  'no-useless-call': NoUselessCall;
  'no-useless-catch': NoUselessCatch;
  'no-useless-computed-key': NoUselessComputedKey;
  'no-useless-concat': NoUselessConcat;
  'no-useless-constructor': NoUselessConstructor;
  'no-useless-escape': NoUselessEscape;
  'no-useless-rename': NoUselessRename;
  'no-useless-return': NoUselessReturn;
  'no-var': NoVar;
  'no-void': NoVoid;
  'no-warning-comments': NoWarningComments;
  'no-whitespace-before-property': NoWhitespaceBeforeProperty;
  'no-with': NoWith;
  'nonblock-statement-body-position': NonblockStatementBodyPosition;
  'object-curly-newline': ObjectCurlyNewline;
  'object-curly-spacing': ObjectCurlySpacing;
  'object-property-newline': ObjectPropertyNewline;
  'object-shorthand': ObjectShorthand;
  'one-var': OneVar;
  'one-var-declaration-per-line': OneVarDeclarationPerLine;
  'operator-assignment': OperatorAssignment;
  'operator-linebreak': OperatorLinebreak;
  'padded-blocks': PaddedBlocks;
  'padding-line-between-statements': PaddingLineBetweenStatements;
  'prefer-arrow-callback': PreferArrowCallback;
  'prefer-const': PreferConst;
  'prefer-destructuring': PreferDestructuring;
  'prefer-exponentiation-operator': PreferExponentiationOperator;
  'prefer-named-capture-group': PreferNamedCaptureGroup;
  'prefer-numeric-literals': PreferNumericLiterals;
  'prefer-object-spread': PreferObjectSpread;
  'prefer-promise-reject-errors': PreferPromiseRejectErrors;
  'prefer-regex-literals': PreferRegexLiterals;
  'prefer-rest-params': PreferRestParams;
  'prefer-spread': PreferSpread;
  'prefer-template': PreferTemplate;
  'quote-props': QuoteProps;
  quotes: Quotes;
  radix: Radix;
  'require-atomic-updates': RequireAtomicUpdates;
  'require-await': RequireAwait;
  'require-unicode-regexp': RequireUnicodeRegexp;
  'require-yield': RequireYield;
  'rest-spread-spacing': RestSpreadSpacing;
  semi: Semi;
  'semi-spacing': SemiSpacing;
  'semi-style': SemiStyle;
  'sort-imports': SortImports;
  'sort-keys': SortKeys;
  'sort-vars': SortVars;
  'space-before-blocks': SpaceBeforeBlocks;
  'space-before-function-paren': SpaceBeforeFunctionParen;
  'space-in-parens': SpaceInParens;
  'space-infix-ops': SpaceInfixOps;
  'space-unary-ops': SpaceUnaryOps;
  'spaced-comment': SpacedComment;
  strict: Strict;
  'switch-colon-spacing': SwitchColonSpacing;
  'symbol-description': SymbolDescription;
  'template-curly-spacing': TemplateCurlySpacing;
  'template-tag-spacing': TemplateTagSpacing;
  'unicode-bom': UnicodeBom;
  'use-isnan': UseIsnan;
  'valid-typeof': ValidTypeof;
  'vars-on-top': VarsOnTop;
  'wrap-iife': WrapIife;
  'wrap-regex': WrapRegex;
  'yield-star-spacing': YieldStarSpacing;
  yoda: Yoda;
}

export { Eslint };
