// this file is auto-generated. Run `make regenerate-types` to regenerate it.

type MemberOrdering0 =
  | []
  | ['off' | 'error' | 'warn']
  | [
      'off' | 'error' | 'warn',
      {
        default?:
          | 'never'
          | (
              | 'signature'
              | 'field'
              | 'public-field'
              | 'public-decorated-field'
              | 'decorated-field'
              | 'static-field'
              | 'public-static-field'
              | 'instance-field'
              | 'public-instance-field'
              | 'abstract-field'
              | 'public-abstract-field'
              | 'protected-field'
              | 'protected-decorated-field'
              | 'protected-static-field'
              | 'protected-instance-field'
              | 'protected-abstract-field'
              | 'private-field'
              | 'private-decorated-field'
              | 'private-static-field'
              | 'private-instance-field'
              | 'private-abstract-field'
              | 'method'
              | 'public-method'
              | 'public-decorated-method'
              | 'decorated-method'
              | 'static-method'
              | 'public-static-method'
              | 'instance-method'
              | 'public-instance-method'
              | 'abstract-method'
              | 'public-abstract-method'
              | 'protected-method'
              | 'protected-decorated-method'
              | 'protected-static-method'
              | 'protected-instance-method'
              | 'protected-abstract-method'
              | 'private-method'
              | 'private-decorated-method'
              | 'private-static-method'
              | 'private-instance-method'
              | 'private-abstract-method'
              | 'constructor'
              | 'public-constructor'
              | 'protected-constructor'
              | 'private-constructor'
            )[]
          | {
              memberTypes?:
                | (
                    | 'signature'
                    | 'field'
                    | 'public-field'
                    | 'public-decorated-field'
                    | 'decorated-field'
                    | 'static-field'
                    | 'public-static-field'
                    | 'instance-field'
                    | 'public-instance-field'
                    | 'abstract-field'
                    | 'public-abstract-field'
                    | 'protected-field'
                    | 'protected-decorated-field'
                    | 'protected-static-field'
                    | 'protected-instance-field'
                    | 'protected-abstract-field'
                    | 'private-field'
                    | 'private-decorated-field'
                    | 'private-static-field'
                    | 'private-instance-field'
                    | 'private-abstract-field'
                    | 'method'
                    | 'public-method'
                    | 'public-decorated-method'
                    | 'decorated-method'
                    | 'static-method'
                    | 'public-static-method'
                    | 'instance-method'
                    | 'public-instance-method'
                    | 'abstract-method'
                    | 'public-abstract-method'
                    | 'protected-method'
                    | 'protected-decorated-method'
                    | 'protected-static-method'
                    | 'protected-instance-method'
                    | 'protected-abstract-method'
                    | 'private-method'
                    | 'private-decorated-method'
                    | 'private-static-method'
                    | 'private-instance-method'
                    | 'private-abstract-method'
                    | 'constructor'
                    | 'public-constructor'
                    | 'protected-constructor'
                    | 'private-constructor'
                  )[]
                | 'never';
              order?: 'alphabetically' | 'as-written';
            };
        classes?:
          | 'never'
          | (
              | 'signature'
              | 'field'
              | 'public-field'
              | 'public-decorated-field'
              | 'decorated-field'
              | 'static-field'
              | 'public-static-field'
              | 'instance-field'
              | 'public-instance-field'
              | 'abstract-field'
              | 'public-abstract-field'
              | 'protected-field'
              | 'protected-decorated-field'
              | 'protected-static-field'
              | 'protected-instance-field'
              | 'protected-abstract-field'
              | 'private-field'
              | 'private-decorated-field'
              | 'private-static-field'
              | 'private-instance-field'
              | 'private-abstract-field'
              | 'method'
              | 'public-method'
              | 'public-decorated-method'
              | 'decorated-method'
              | 'static-method'
              | 'public-static-method'
              | 'instance-method'
              | 'public-instance-method'
              | 'abstract-method'
              | 'public-abstract-method'
              | 'protected-method'
              | 'protected-decorated-method'
              | 'protected-static-method'
              | 'protected-instance-method'
              | 'protected-abstract-method'
              | 'private-method'
              | 'private-decorated-method'
              | 'private-static-method'
              | 'private-instance-method'
              | 'private-abstract-method'
              | 'constructor'
              | 'public-constructor'
              | 'protected-constructor'
              | 'private-constructor'
            )[]
          | {
              memberTypes?:
                | (
                    | 'signature'
                    | 'field'
                    | 'public-field'
                    | 'public-decorated-field'
                    | 'decorated-field'
                    | 'static-field'
                    | 'public-static-field'
                    | 'instance-field'
                    | 'public-instance-field'
                    | 'abstract-field'
                    | 'public-abstract-field'
                    | 'protected-field'
                    | 'protected-decorated-field'
                    | 'protected-static-field'
                    | 'protected-instance-field'
                    | 'protected-abstract-field'
                    | 'private-field'
                    | 'private-decorated-field'
                    | 'private-static-field'
                    | 'private-instance-field'
                    | 'private-abstract-field'
                    | 'method'
                    | 'public-method'
                    | 'public-decorated-method'
                    | 'decorated-method'
                    | 'static-method'
                    | 'public-static-method'
                    | 'instance-method'
                    | 'public-instance-method'
                    | 'abstract-method'
                    | 'public-abstract-method'
                    | 'protected-method'
                    | 'protected-decorated-method'
                    | 'protected-static-method'
                    | 'protected-instance-method'
                    | 'protected-abstract-method'
                    | 'private-method'
                    | 'private-decorated-method'
                    | 'private-static-method'
                    | 'private-instance-method'
                    | 'private-abstract-method'
                    | 'constructor'
                    | 'public-constructor'
                    | 'protected-constructor'
                    | 'private-constructor'
                  )[]
                | 'never';
              order?: 'alphabetically' | 'as-written';
            };
        classExpressions?:
          | 'never'
          | (
              | 'signature'
              | 'field'
              | 'public-field'
              | 'public-decorated-field'
              | 'decorated-field'
              | 'static-field'
              | 'public-static-field'
              | 'instance-field'
              | 'public-instance-field'
              | 'abstract-field'
              | 'public-abstract-field'
              | 'protected-field'
              | 'protected-decorated-field'
              | 'protected-static-field'
              | 'protected-instance-field'
              | 'protected-abstract-field'
              | 'private-field'
              | 'private-decorated-field'
              | 'private-static-field'
              | 'private-instance-field'
              | 'private-abstract-field'
              | 'method'
              | 'public-method'
              | 'public-decorated-method'
              | 'decorated-method'
              | 'static-method'
              | 'public-static-method'
              | 'instance-method'
              | 'public-instance-method'
              | 'abstract-method'
              | 'public-abstract-method'
              | 'protected-method'
              | 'protected-decorated-method'
              | 'protected-static-method'
              | 'protected-instance-method'
              | 'protected-abstract-method'
              | 'private-method'
              | 'private-decorated-method'
              | 'private-static-method'
              | 'private-instance-method'
              | 'private-abstract-method'
              | 'constructor'
              | 'public-constructor'
              | 'protected-constructor'
              | 'private-constructor'
            )[]
          | {
              memberTypes?:
                | (
                    | 'signature'
                    | 'field'
                    | 'public-field'
                    | 'public-decorated-field'
                    | 'decorated-field'
                    | 'static-field'
                    | 'public-static-field'
                    | 'instance-field'
                    | 'public-instance-field'
                    | 'abstract-field'
                    | 'public-abstract-field'
                    | 'protected-field'
                    | 'protected-decorated-field'
                    | 'protected-static-field'
                    | 'protected-instance-field'
                    | 'protected-abstract-field'
                    | 'private-field'
                    | 'private-decorated-field'
                    | 'private-static-field'
                    | 'private-instance-field'
                    | 'private-abstract-field'
                    | 'method'
                    | 'public-method'
                    | 'public-decorated-method'
                    | 'decorated-method'
                    | 'static-method'
                    | 'public-static-method'
                    | 'instance-method'
                    | 'public-instance-method'
                    | 'abstract-method'
                    | 'public-abstract-method'
                    | 'protected-method'
                    | 'protected-decorated-method'
                    | 'protected-static-method'
                    | 'protected-instance-method'
                    | 'protected-abstract-method'
                    | 'private-method'
                    | 'private-decorated-method'
                    | 'private-static-method'
                    | 'private-instance-method'
                    | 'private-abstract-method'
                    | 'constructor'
                    | 'public-constructor'
                    | 'protected-constructor'
                    | 'private-constructor'
                  )[]
                | 'never';
              order?: 'alphabetically' | 'as-written';
            };
        interfaces?:
          | 'never'
          | ('signature' | 'field' | 'method' | 'constructor')[]
          | {
              memberTypes?:
                | ('signature' | 'field' | 'method' | 'constructor')[]
                | 'never';
              order?: 'alphabetically' | 'as-written';
            };
        typeLiterals?:
          | 'never'
          | ('signature' | 'field' | 'method' | 'constructor')[]
          | {
              memberTypes?:
                | ('signature' | 'field' | 'method' | 'constructor')[]
                | 'never';
              order?: 'alphabetically' | 'as-written';
            };
      },
    ];

export type MemberOrdering = 'off' | MemberOrdering0;
