// this file is auto-generated. Run `make regenerate-types` to regenerate it.

import { BooleanPropNaming } from '../react/boolean-prop-naming';
import { ButtonHasType } from '../react/button-has-type';
import { DefaultPropsMatchPropTypes } from '../react/default-props-match-prop-types';
import { DestructuringAssignment } from '../react/destructuring-assignment';
import { DisplayName } from '../react/display-name';
import { ForbidComponentProps } from '../react/forbid-component-props';
import { ForbidDomProps } from '../react/forbid-dom-props';
import { ForbidElements } from '../react/forbid-elements';
import { ForbidForeignPropTypes } from '../react/forbid-foreign-prop-types';
import { ForbidPropTypes } from '../react/forbid-prop-types';
import { JsxBooleanValue } from '../react/jsx-boolean-value';
import { JsxChildElementSpacing } from '../react/jsx-child-element-spacing';
import { JsxClosingBracketLocation } from '../react/jsx-closing-bracket-location';
import { JsxClosingTagLocation } from '../react/jsx-closing-tag-location';
import { JsxCurlyBracePresence } from '../react/jsx-curly-brace-presence';
import { JsxCurlyNewline } from '../react/jsx-curly-newline';
import { JsxCurlySpacing } from '../react/jsx-curly-spacing';
import { JsxEqualsSpacing } from '../react/jsx-equals-spacing';
import { JsxFilenameExtension } from '../react/jsx-filename-extension';
import { JsxFirstPropNewLine } from '../react/jsx-first-prop-new-line';
import { JsxFragments } from '../react/jsx-fragments';
import { JsxHandlerNames } from '../react/jsx-handler-names';
import { JsxIndent } from '../react/jsx-indent';
import { JsxIndentProps } from '../react/jsx-indent-props';
import { JsxKey } from '../react/jsx-key';
import { JsxMaxDepth } from '../react/jsx-max-depth';
import { JsxMaxPropsPerLine } from '../react/jsx-max-props-per-line';
import { JsxNoBind } from '../react/jsx-no-bind';
import { JsxNoCommentTextnodes } from '../react/jsx-no-comment-textnodes';
import { JsxNoDuplicateProps } from '../react/jsx-no-duplicate-props';
import { JsxNoLiterals } from '../react/jsx-no-literals';
import { JsxNoTargetBlank } from '../react/jsx-no-target-blank';
import { JsxNoUndef } from '../react/jsx-no-undef';
import { JsxOneExpressionPerLine } from '../react/jsx-one-expression-per-line';
import { JsxPascalCase } from '../react/jsx-pascal-case';
import { JsxPropsNoMultiSpaces } from '../react/jsx-props-no-multi-spaces';
import { JsxPropsNoSpreading } from '../react/jsx-props-no-spreading';
import { JsxSortDefaultProps } from '../react/jsx-sort-default-props';
import { JsxSortProps } from '../react/jsx-sort-props';
import { JsxTagSpacing } from '../react/jsx-tag-spacing';
import { JsxUsesReact } from '../react/jsx-uses-react';
import { JsxUsesVars } from '../react/jsx-uses-vars';
import { JsxWrapMultilines } from '../react/jsx-wrap-multilines';
import { NoAccessStateInSetstate } from '../react/no-access-state-in-setstate';
import { NoArrayIndexKey } from '../react/no-array-index-key';
import { NoChildrenProp } from '../react/no-children-prop';
import { NoDanger } from '../react/no-danger';
import { NoDangerWithChildren } from '../react/no-danger-with-children';
import { NoDeprecated } from '../react/no-deprecated';
import { NoDidMountSetState } from '../react/no-did-mount-set-state';
import { NoDidUpdateSetState } from '../react/no-did-update-set-state';
import { NoDirectMutationState } from '../react/no-direct-mutation-state';
import { NoFindDomNode } from '../react/no-find-dom-node';
import { NoIsMounted } from '../react/no-is-mounted';
import { NoMultiComp } from '../react/no-multi-comp';
import { NoRedundantShouldComponentUpdate } from '../react/no-redundant-should-component-update';
import { NoRenderReturnValue } from '../react/no-render-return-value';
import { NoSetState } from '../react/no-set-state';
import { NoStringRefs } from '../react/no-string-refs';
import { NoThisInSfc } from '../react/no-this-in-sfc';
import { NoTypos } from '../react/no-typos';
import { NoUnescapedEntities } from '../react/no-unescaped-entities';
import { NoUnknownProperty } from '../react/no-unknown-property';
import { NoUnsafe } from '../react/no-unsafe';
import { NoUnusedPropTypes } from '../react/no-unused-prop-types';
import { NoUnusedState } from '../react/no-unused-state';
import { NoWillUpdateSetState } from '../react/no-will-update-set-state';
import { PreferEs6Class } from '../react/prefer-es6-class';
import { PreferReadOnlyProps } from '../react/prefer-read-only-props';
import { PreferStatelessFunction } from '../react/prefer-stateless-function';
import { PropTypes } from '../react/prop-types';
import { ReactInJsxScope } from '../react/react-in-jsx-scope';
import { RequireDefaultProps } from '../react/require-default-props';
import { RequireOptimization } from '../react/require-optimization';
import { RequireRenderReturn } from '../react/require-render-return';
import { SelfClosingComp } from '../react/self-closing-comp';
import { SortComp } from '../react/sort-comp';
import { SortPropTypes } from '../react/sort-prop-types';
import { StateInConstructor } from '../react/state-in-constructor';
import { StaticPropertyPlacement } from '../react/static-property-placement';
import { StylePropObject } from '../react/style-prop-object';
import { VoidDomElementsNoChildren } from '../react/void-dom-elements-no-children';

interface React {
  'react/boolean-prop-naming': BooleanPropNaming;
  'react/button-has-type': ButtonHasType;
  'react/default-props-match-prop-types': DefaultPropsMatchPropTypes;
  'react/destructuring-assignment': DestructuringAssignment;
  'react/display-name': DisplayName;
  'react/forbid-component-props': ForbidComponentProps;
  'react/forbid-dom-props': ForbidDomProps;
  'react/forbid-elements': ForbidElements;
  'react/forbid-foreign-prop-types': ForbidForeignPropTypes;
  'react/forbid-prop-types': ForbidPropTypes;
  'react/jsx-boolean-value': JsxBooleanValue;
  'react/jsx-child-element-spacing': JsxChildElementSpacing;
  'react/jsx-closing-bracket-location': JsxClosingBracketLocation;
  'react/jsx-closing-tag-location': JsxClosingTagLocation;
  'react/jsx-curly-brace-presence': JsxCurlyBracePresence;
  'react/jsx-curly-newline': JsxCurlyNewline;
  'react/jsx-curly-spacing': JsxCurlySpacing;
  'react/jsx-equals-spacing': JsxEqualsSpacing;
  'react/jsx-filename-extension': JsxFilenameExtension;
  'react/jsx-first-prop-new-line': JsxFirstPropNewLine;
  'react/jsx-fragments': JsxFragments;
  'react/jsx-handler-names': JsxHandlerNames;
  'react/jsx-indent': JsxIndent;
  'react/jsx-indent-props': JsxIndentProps;
  'react/jsx-key': JsxKey;
  'react/jsx-max-depth': JsxMaxDepth;
  'react/jsx-max-props-per-line': JsxMaxPropsPerLine;
  'react/jsx-no-bind': JsxNoBind;
  'react/jsx-no-comment-textnodes': JsxNoCommentTextnodes;
  'react/jsx-no-duplicate-props': JsxNoDuplicateProps;
  'react/jsx-no-literals': JsxNoLiterals;
  'react/jsx-no-target-blank': JsxNoTargetBlank;
  'react/jsx-no-undef': JsxNoUndef;
  'react/jsx-one-expression-per-line': JsxOneExpressionPerLine;
  'react/jsx-pascal-case': JsxPascalCase;
  'react/jsx-props-no-multi-spaces': JsxPropsNoMultiSpaces;
  'react/jsx-props-no-spreading': JsxPropsNoSpreading;
  'react/jsx-sort-default-props': JsxSortDefaultProps;
  'react/jsx-sort-props': JsxSortProps;
  'react/jsx-tag-spacing': JsxTagSpacing;
  'react/jsx-uses-react': JsxUsesReact;
  'react/jsx-uses-vars': JsxUsesVars;
  'react/jsx-wrap-multilines': JsxWrapMultilines;
  'react/no-access-state-in-setstate': NoAccessStateInSetstate;
  'react/no-array-index-key': NoArrayIndexKey;
  'react/no-children-prop': NoChildrenProp;
  'react/no-danger': NoDanger;
  'react/no-danger-with-children': NoDangerWithChildren;
  'react/no-deprecated': NoDeprecated;
  'react/no-did-mount-set-state': NoDidMountSetState;
  'react/no-did-update-set-state': NoDidUpdateSetState;
  'react/no-direct-mutation-state': NoDirectMutationState;
  'react/no-find-dom-node': NoFindDomNode;
  'react/no-is-mounted': NoIsMounted;
  'react/no-multi-comp': NoMultiComp;
  'react/no-redundant-should-component-update': NoRedundantShouldComponentUpdate;
  'react/no-render-return-value': NoRenderReturnValue;
  'react/no-set-state': NoSetState;
  'react/no-string-refs': NoStringRefs;
  'react/no-this-in-sfc': NoThisInSfc;
  'react/no-typos': NoTypos;
  'react/no-unescaped-entities': NoUnescapedEntities;
  'react/no-unknown-property': NoUnknownProperty;
  'react/no-unsafe': NoUnsafe;
  'react/no-unused-prop-types': NoUnusedPropTypes;
  'react/no-unused-state': NoUnusedState;
  'react/no-will-update-set-state': NoWillUpdateSetState;
  'react/prefer-es6-class': PreferEs6Class;
  'react/prefer-read-only-props': PreferReadOnlyProps;
  'react/prefer-stateless-function': PreferStatelessFunction;
  'react/prop-types': PropTypes;
  'react/react-in-jsx-scope': ReactInJsxScope;
  'react/require-default-props': RequireDefaultProps;
  'react/require-optimization': RequireOptimization;
  'react/require-render-return': RequireRenderReturn;
  'react/self-closing-comp': SelfClosingComp;
  'react/sort-comp': SortComp;
  'react/sort-prop-types': SortPropTypes;
  'react/state-in-constructor': StateInConstructor;
  'react/static-property-placement': StaticPropertyPlacement;
  'react/style-prop-object': StylePropObject;
  'react/void-dom-elements-no-children': VoidDomElementsNoChildren;
}

export { React };
